### ISSUE TITLE
week view / stats

### ISSUE THREAD

**Issue by rrd108** [rrd108/sadhana#33]
![Képernyőkép ekkor: 2023-04-01 17-08-39](https://user-images.githubusercontent.com/3147489/229297381-a88bf5ac-5ea4-4975-8b3c-449096bbed3c.png)

**Comment by rrd108** [comment]
On the leadersvoard if i clcik on my own name I get a week info.

This is the same but it does not show the data by day, but by sadhana activity type, like on the example above.

**Comment by thomashisgithub** [comment]
14f62f6
