### ISSUE TITLE
Lazy loading breaks fallback locale

### ISSUE THREAD

**Issue by thomashisgithub** [rrd108/sadhana#58]
Before we loaded both English and Hungarian locales.
Since English locale is incomplete it would fall back to Hungarian.
Now we don't load Hungarian anymore if English is selected and therefore fallback locale is not working.

Solutions:
1) always load one fallback locale (defeats part of the lazy loading)
2) implement logic to load fallback locale if missing translation is found (difficult)
3) stop using the fallback locale feature while no second locale is loaded (current situation)

**Comment by rrd108** [comment]
I think option 3 is totally acceptable
